### ISSUE TITLE
[Feature Request] Disable signup

### ISSUE THREAD

**Issue by Synt3x** [linuxserver/docker-healthchecks#34]
Hello, in the official Healthchecks documentation, you could disable signup. Is it possible to add this as an environment to Linuxserver.io version of Healthchecks?

[Documentation link](https://github.com/healthchecks/healthchecks#configuration ) > REGISTRATION_OPEN

**Comment by LsHallo** [comment]
You can go into the config folder that you specified when setting up the docker container and edit local_settings.py
Add the line `REGISTRATION_OPEN = False` and restart the container and you are set.

**Comment by Synt3x** [comment]
@LsHallo Thanks for the information, but I have already done this. One of the many good thing with docker is how easy it is to setup services. It's easier and more handy if you just could change the docker-compose setting and it will apply for the container. This is how many other containers work, no extra steps to set it up.

Anyway, thanks for the help and concern!

**Comment by tobbenb** [comment]
If healthchecks read the value from a env variable, you can add it in your compose and healthchecks should be able to use it.

**Comment by Synt3x** [comment]
@tobbenb have you tried it?

**Comment by tobbenb** [comment]
No, but you can?
I don't understand why I should read your first post again?

Our container doesn't need to add support for the environment variable if healthchecks already read it from the environment variable. Then you simply add it in your compose file.

**Comment by skyfrk** [comment]
I just tested this `docker-compose.yml` file:

```yaml
version: '3'

services:
    healthchecks:
        image: linuxserver/healthchecks
        environment:
            - PUID=1000
            - PGID=1000
            - SITE_ROOT
            - SITE_NAME
            - DEFAULT_FROM_EMAIL
            - EMAIL_HOST
            - EMAIL_PORT
            - EMAIL_HOST_USER
            - EMAIL_HOST_PASSWORD
            - EMAIL_USE_TLS=True
            - ALLOWED_HOSTS
            - SUPERUSER_EMAIL
            - SUPERUSER_PASSWORD
            - REGISTRATION_OPEN=False
        volumes:
            - config:/config
        restart: unless-stopped

volumes:
    config:
```

`REGISTRATION_OPEN` works with `linuxserver/healthchecks` out of the box!

![image](https://user-images.githubusercontent.com/27026029/80868896-85c11880-8c9d-11ea-9ec7-31afe561cb0c.png)

However I agree with @Synt3x that linuxserver should at least mention `REGISTRATION_OPEN` in the docs 🤔.
