### ISSUE TITLE
Bad request  - Error 400

### ISSUE THREAD

**Issue by Braincoke** [linuxserver/docker-healthchecks#38]
Here is an error I encountered with its solution.

## Expected Behavior

When using the docker-compose.yml file below and starting it with `docker-compose up` the application should work.

```yml
version: '2'
services:
  healthchecks:
    container_name: 'healthchecks'
    image: linuxserver/healthchecks:latest
    environment:
      - PUID=1000
      - PGID=1000
      - ALLOWED_HOSTS=["*"]
      - DEBUG=True
    volumes:
      - ./healthchecks_data:/config
    networks:
      host-macvlan-net:
        ipv4_address: 10.0.6.10
networks:
  host-macvlan-net:
    external:
      name: host-macvlan-net
```

## Current Behavior

The docker seems to start properly without yielding errors but trying to access the application returns 400 errors.
```
GET / => generated 143 bytes in 85 msecs (HTTP/1.1 400) 2 headers in 86 bytes (1 switches on core 0)
```
This is usually a sign that "ALLOWED_HOSTS" is not properly configured but I did include the environment variable in the docker-compose file.

## Solution

The mounted volume `/config` contains a file `local_settings.py` that seems to take precedence over the environment variables :

```python
EMAIL_HOST = "smtp.gmail.com"
DEFAULT_FROM_EMAIL = "noreply@example.com"
BASE_URL = "healthchecks.example.com"
EMAIL_USE_TLS = True
SITE_ROOT = "https://healthchecks.example.com"
DEBUG = False
EMAIL_PORT = "587"
SITE_NAME = "healthchecks"
EMAIL_HOST_PASSWORD = "password"
EMAIL_HOST_USER = "username"
ALLOWED_HOSTS = ["healthchecks.example.com"]
CSRF_TRUSTED_ORIGINS = ["healthchecks.example.com"]
```
The solution is to modify the parameters directly in this file. Hope this saves some time for someone else.
