### ISSUE TITLE
$CSRF_HOST Related Bash Error

### ISSUE THREAD

**Issue by GSeibt** [linuxserver/docker-healthchecks#47]
## Expected Behavior
No errors in the Docker log when running the container.

## Current Behavior
Docker logs contain errors when running the container. 

Docker logs contain the following errors when running the container:

```
/var/run/s6/etc/cont-init.d/30-config: line 30: https://our.url.com/: No such file or directory
/var/run/s6/etc/cont-init.d/30-config: line 30: =: command not found
```
Line 30 is:
https://github.com/linuxserver/docker-healthchecks/blob/e85ecaa260d3f0345ddd98ced4145a8672a9b1a3/root/etc/cont-init.d/30-config#L30

It was introduced as part of Issue #22.

Frankly I have no idea what that line is supposed to do. Dereferencing a variable left of the `=` and passing a URL to a subshell just doesn't make sense to me. I am far from a Bash expert though.

The subshell produces the first error since there is no directory named `https://our.url.com/`. Even if it were to exist, the result would be `-bash: https://our.url.com/: Is a directory`. The variable `$CSRF_HOST` is empty / undefined and Bash then attempts to execute `=` as a command which does not exist. 

I have done extensive research but can't find any reference to "$CSRF_HOST" (literally, Google returns 0 results). Closest I have come is the documentation of the CSRF protection module of Django 3 but I have found no mention of that variable. 

So... I don't know, is that line simply wrong?

The service is running despite the errors... I haven't tested any functionality yet though.

## Steps to Reproduce
Simply start the container as below.

## Environment
**OS:**  Linux HOST 4.9.0-12-amd64 #&#8203;1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux    
**CPU architecture:** x86_64
**How docker service was installed:** [This way.](https://docs.docker.com/engine/install/debian/#install-using-the-repository)

## Command used to create docker container (run/create/compose/screenshot)
`docker stack deploy -c hc.yml healthchecks`
```yaml
version: "3.8"
services:
  healthchecks:
    image: linuxserver/healthchecks
    environment:
      - PUID=1000
      - PGID=1000
      - SITE_ROOT=https://our.url.com
      - SITE_NAME=Our Name
      - DEFAULT_FROM_EMAIL=Our Email
      - EMAIL_HOST=Our SMTP Host
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=Our SMTP User
      - FILE__EMAIL_HOST_PASSWORD=/run/secrets/smtp_pw
      - EMAIL_USE_TLS=True
      - ALLOWED_HOSTS=["*"]
      - SUPERUSER_EMAIL=Our Superuser Email
      - FILE__SUPERUSER_PASSWORD=/run/secrets/superuser_pw
    volumes:
      - data:/config
    ports:
      - 8000:8000
    deploy:
      restart_policy: 
        condition: on-failure
    secrets:
      - smtp_pw
      - superuser_pw

volumes:
  data:

secrets:
  smtp_pw: 
    file: ./smtp_pw
  superuser_pw:
    file: ./superuser_pw
```

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[env-init] EMAIL_HOST_PASSWORD set from FILE__EMAIL_HOST_PASSWORD
[env-init] SUPERUSER_PASSWORD set from FILE__SUPERUSER_PASSWORD
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
/var/run/s6/etc/cont-init.d/30-config: line 30: https://rone.fim.uni-passau.de/: No such file or directory
/var/run/s6/etc/cont-init.d/30-config: line 30: =: command not found
Operations to perform:
  Apply all migrations: accounts, admin, api, auth, contenttypes, payments, sessions
Running migrations:
[...]
```
