### ISSUE TITLE
SITE_ROOT set but emails still being generated with `example.com`

### ISSUE THREAD

**Issue by dalanmiller** [linuxserver/docker-healthchecks#53]
## Expected Behavior
With `SITE_ROOT` set expecting that email links use that for links.

## Current Behavior
Emails using default `example.com` 

## Environment
**OS:**  Ubuntu 20.04
**CPU architecture:** x86_64
**How docker service was installed:**   apt install docker

## Command used to create docker container (run/create/compose/screenshot)
`docker-compose up --detach`

config.yml:
```
healthchecks:
    container_name: healthchecks
    image: linuxserver/healthchecks
    restart: unless-stopped
    volumes:
      - /nfs/docker/healthchecks:/config
    environment:
      - PGID=1000
      - PUID=1000
      - SITE_ROOT=https://healthchecks.subdomain.domain.com
      - SITE_NAME="DalanHealthyChecks"
      - DEFAULT_FROM_EMAIL=healthchecks@domain.com
      - EMAIL_HOST=smtp.emailapi.net
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=apikey
      - EMAIL_HOST_PASSWORD="holdontoyourbutts"
      - EMAIL_USE_TLS=True
```
