### ISSUE TITLE
Feature Request: Support Receiving Email Pings

### ISSUE THREAD

**Issue by comnam90** [linuxserver/docker-healthchecks#55]
Healthchecks application is designed to also accept email pings as well as http pings, but the container needs to be configured to listen for SMTP requests.

Official docs on it: https://github.com/healthchecks/healthchecks#receiving-emails

------------------------------

## Expected Behavior

Container supports environment variable to enabling and configuring SMTPd in the container for SMTP Pings

## Current Behavior

There is no support for SMTPd or SMTP Pings

## Environment

**OS:**      Ubuntu 18.04
**CPU architecture:** x86_64
**How docker service was installed:**      apt repo

## Command used to create docker container (run/create/compose/screenshot)

```
version: "2.1"
services:
  healthchecks:
    image: linuxserver/healthchecks
    container_name: healthchecks
    environment:
      - PUID=1000
      - PGID=1000
      - SITE_ROOT={REDACTED}
      - SITE_NAME={REDACTED}
      - DEFAULT_FROM_EMAIL={REDACTED}
      - EMAIL_HOST=192.168.1.28
      - EMAIL_PORT=2525
      - EMAIL_HOST_USER={REDACTED}
      - EMAIL_HOST_PASSWORD={REDACTED}
      - EMAIL_USE_TLS=False
      - SUPERUSER_EMAIL={REDACTED}
      - SUPERUSER_PASSWORD={REDACTED}
      - DOCKER_MODS=linuxserver/mods:healthchecks-apprise
      - SERVICE_TAGS=traefik.frontend.redirect.entryPoint=https,traefik.frontends.int.rule=Host:{{.ServiceName}}.int.{{.Domain}},traefik.frontends.ext.rule=Host:hc.{{.Domain}},traefik.frontend.headers.SSLRedirect=true,traefik.frontend.passHostHeader=true
      - SERVICE_NAME=healthchecks
    volumes:
      - ./config:/config
    ports:
      - 8000:8000
    restart: unless-stopped
```
