### ISSUE TITLE
Healthchecks v1.22.0 introduces Whitenoise and so web interface won't start with debug=False

### ISSUE THREAD

**Issue by immanuelfodor** [linuxserver/docker-healthchecks#71]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Web interface starts up fine with debug=False

## Current Behavior

Server Error (500) is shown on the main page. 

The issue is related to https://github.com/healthchecks/healthchecks/issues/548 and https://github.com/healthchecks/healthchecks/commit/e6427995b7ad22a70beb463365f015867d2b000c

## Steps to Reproduce

1. Start the latest docker image
2. Visit the web interface
3. White page with black error text is shown: Server Error (500)

## Environment
**OS:** CentOS Stream
**CPU architecture:** x86_64
**How docker service was installed:** Official, unrelated to the issue

Image: https://github.com/linuxserver/docker-healthchecks/pkgs/container/healthchecks/6262292

## Command used to create docker container (run/create/compose/screenshot)

Kubernetes deployment with debug env var set to False

## Docker logs

```
...
*** Operational MODE: single process ***
running "exec:/usr/bin/python3 ./manage.py collectstatic --noinput" (pre app)...
Traceback (most recent call last):
  File "/app/healthchecks/./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.9/site-packages/django/core/management/__init__.py", line
419, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.9/site-packages/django/core/management/__init__.py", line
413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.9/site-packages/django/core/management/base.py", line 354,
 in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.9/site-packages/django/core/management/base.py", line 398,
 in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.9/site-packages/django/contrib/staticfiles/management/comm
ands/collectstatic.py", line 187, in handle
    collected = self.collect()
  File "/usr/lib/python3.9/site-packages/django/contrib/staticfiles/management/comm
ands/collectstatic.py", line 114, in collect
    handler(path, prefixed_path, storage)
  File "/usr/lib/python3.9/site-packages/django/contrib/staticfiles/management/comm
ands/collectstatic.py", line 347, in copy_file
    with source_storage.open(path) as source_file:
  File "/usr/lib/python3.9/site-packages/django/core/files/storage.py", line 38, in
 open
    return self._open(name, mode)
  File "/usr/lib/python3.9/site-packages/django/core/files/storage.py", line 238, i
n _open
    return File(open(self.path(name), mode))
FileNotFoundError: [Errno 2] No such file or directory: '/app/healthchecks/static/i
mg/logo@2x.png'
command "/usr/bin/python3 ./manage.py collectstatic --noinput" exited with non-zero
 code: 1
Sat Aug  7 18:42:50 2021 - FATAL hook failed, destroying instance
SIGINT/SIGQUIT received...killing workers...
WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0x7ff112869bf0 pid: 31
4 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 314)
spawned uWSGI worker 1 (pid: 330, cores: 1)
[uwsgi-daemons] spawning "/usr/bin/python3 ./manage.py sendalerts" (uid: 1100 gid:
1100)
...
```

Pings are received fine, just the web interface is broken due to the new static file collection fails. I don't have a custom logo set up and run with debug=False (prod mode). Please adjust the image to support the new static file serving lib, Whitenoise, when running in prod mode.

**Comment by TheSpad** [comment]
I can't replicate this, I've got v1.22.0 running with `debug=False` and I'm not seeing any problems with the web interface. Can you provide your run/compose?

My logs
```
*** Operational MODE: single process ***
running "exec:/usr/bin/python3 ./manage.py collectstatic --noinput" (pre app)...

321 static files copied to '/app/healthchecks/static-collected'.
running "exec:/usr/bin/python3 ./manage.py compress" (pre app)...
Compressing... done
Compressed 24 block(s) from 126 template(s) for 0 context(s).
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7fcbd002abf0 pid: 292 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 292)
spawned uWSGI worker 1 (pid: 306, cores: 1)
[uwsgi-daemons] spawning "/usr/bin/python3 ./manage.py sendalerts" (uid: 1000 gid: 1000)
```

**Comment by immanuelfodor** [comment]
I can also see these lines but I haven't changed a thing, just updated to the new image: 

```
...
-------------------------------------
GID/UID
-------------------------------------
User uid:    1100
User gid:    1100
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
cp: cannot stat '/app/healthchecks/static/img/logo@2x.png': No such file or directo
ry
cp: cannot stat '/app/healthchecks/static/img/logo-512-green.png': No such file or
directory
cp: cannot stat '/app/healthchecks/static/img/logo-full@2x.png': No such file or di
rectory
cp: cannot stat '/app/healthchecks/static/img/logo-full.png': No such file or direc
tory
Operations to perform:
  Apply all migrations: accounts, admin, api, auth, contenttypes, payments, session
s
Running migrations:
  No migrations to apply.
Superuser creation skipped. Already exists.
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
...
```

There is no compose file, I'm running it in k8s. Envs are the following: 

```
  PUID: "1100"
  PGID: "1100"
  TZ: "Europe/Budapest"
  SITE_ROOT: "https://h.example.com"
  SITE_NAME: "Healthchecks"
  DEFAULT_FROM_EMAIL: "..."
  EMAIL_HOST: "..."
  EMAIL_PORT: "25"
  EMAIL_HOST_USER: "False"
  EMAIL_HOST_PASSWORD: "False"
  EMAIL_USE_TLS: "False"
  ALLOWED_HOSTS: "*"
  APPRISE_ENABLED: "True"
  SECRET_KEY: "..."
  SUPERUSER_EMAIL: "..."                                   SUPERUSER_PASSWORD: "..."
  DB: "postgres"
  DB_HOST: "192.168.1.5"
  DB_PORT: "5432"
  DB_SSLMODE: "disable"
  DB_NAME: "healthchecks"
  DB_USER: "healthchecks"
  DB_PASSWORD: "..."
```

The startup command is a bit modified to enable Apprise but that's all, simple deployment: 

```
spec:
  selector:
    matchLabels:
      app: healthchecks
  template:
    metadata:
      labels:
        app: healthchecks                                                          
    spec:
      containers:
        - name: healthchecks
          image: "ghcr.io/linuxserver/healthchecks:amd64-latest"
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: healthchecks-config
          command: ["/bin/sh"]
          args:
            - -c
            - echo "Adding apprise from k8s command..."
              && pip3 install apprise
              && echo "Running original entrypoint '/init' from https://github.com/linuxserver/docker-baseimage-alpine/blob/master/Dockerfile"
              && /init
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
```

No volume or anything, using PG as DB.
