### ISSUE TITLE
Exception Value: no such table: django_session

### ISSUE THREAD

**Issue by Whisper40** [linuxserver/docker-healthchecks#88]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
I should be able to connect to the interface

## Current Behavior

I was registering my account after the first init, then it throws no such table: django_session
## Steps to Reproduce

1. Fresh install with this docker-compose
2. Try to register
3. It fails
4.

## Environment
**OS:** Docker
**CPU architecture:** x86_64
**How docker service was installed:**

## Command used to create docker container (run/create/compose/screenshot)
```
healthchecksio:
    image: linuxserver/healthchecks:2.0.1
    container_name: pprod_healthchecksio
    restart: unless-stopped
    environment:
      - SITE_ROOT=healthchecksio.fr
      - SITE_NAME=Monitoring CronTab
      - SUPERUSER_EMAIL=toto@titi.com
      - SUPERUSER_PASSWORD=INeedToGenerateAPasswordHere
      - REGENERATE_SETTINGS=True
      - PUID=1000
      - PGID=1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.healthchecksio-pprod-router.entrypoints=websecure"
      - "traefik.http.routers.healthchecksio-pprod-router.rule=Host(`healthchecksio-dependencies-scan...`,`healthchecksio-dependencies-scan-..`)"
      - "traefik.http.routers.healthchecksio-pprod-router.service=healthchecksio-pprod-service"
      - "traefik.http.routers.healthchecksio-pprod-router.tls=true"
      - "traefik.http.services.healthchecksio-pprod-service.loadbalancer.server.port=8000"
    volumes:
      - ./healthchecksio:/config
    networks:
      - proxy
```
